[package]
name = "jwt"
version = "0.1.0"
authors = ["Sonny Scroggin <sonny@scrogg.in>"]

[dependencies]
rustwt = "1.0.1"
uuid = { version = "0.6.5", features = ["v4"] }
structopt = "0.2.10"
failure = "0.1.2"
